### ISSUE TITLE
Add a link in the chart sidebar to help interpret the numbers

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#104]
Provide a link with the words "How do I interpret these charts?" which links to a help or FAQ page (open in a new window).  @kklausmeyer will provide the content for sample charts an interpretations and some case studies.

**Comment by nathanielrindlaub** [comment]
I added a link at the bottom of the charts that opens a "How to interpret the charts" page in a new tab. We'll need content for this page but I'm going to close this out and open a new issue for that.
