### ISSUE TITLE
Implement download

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/gde#108]
Where should we put the data downloads as described in #98

**Comment by kklausmeyer** [comment]
Ok-  I was thinking this could be a "Data and API" tab, or two separate pages for "Data" and "API".  @nathanielrindlaub what do you think?  I can write up the intro content for the pages.

**Comment by nathanielrindlaub** [comment]
I think just "Data" is fine for the tab name. We can add API documentation in a separate tab or within the Data page once we have it.

**Comment by nathanielrindlaub** [comment]
I think @postfalk knocked this one down at babe5e4
