### ISSUE TITLE
Add additional trend rasters

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#111]
While all possible combinations are not likely, users are interested in the following trends:

1. 2008-2018 NDVI (complete)
2. 2008-2018 NDMI
3. 2014-2018 NDVI
4. 2014-2018 NDMI
5. 1985-2018 NDVI
6. 1985-2018 NDMI

**Comment by kklausmeyer** [comment]
Hi Falk-  I had requested the 2014-2018 raster, not the 2004-2018.  Do you think you can add in the 2014-2018 as well?

**Comment by postfalk** [comment]
Sure will be online in about an hour.

**Comment by postfalk** [comment]
Ok correction:

https://tiles.codefornature.org/tiles/ndvitrend-masked-2009-2018/
https://tiles.codefornature.org/tiles/ndmitrend-masked-2009-2018/
https://tiles.codefornature.org/tiles/ndvitrend-masked-2004-2018/ (not requested by this issue)
https://tiles.codefornature.org/tiles/ndmitrend-masked-2004-2018/ (not requested by this issue)
https://tiles.codefornature.org/tiles/ndvitrend-masked-2014-2018/
https://tiles.codefornature.org/tiles/ndmitrend-masked-2014-2018/
https://tiles.codefornature.org/tiles/ndvitrend-masked-1985-2018/
https://tiles.codefornature.org/tiles/ndmitrend-masked-1985-2018/

**Comment by nathanielrindlaub** [comment]
Also looks like the original request was for NDVI & NDMI 2008-2018, not 2009-2018. Was that a typo @postfalk are those tiles from 2009 onwards?

**Comment by postfalk** [comment]
@nathanielrindlaub It has been an error in that regard that we actually aggregated 11 years originally which has been corrected. However, the original label reflected the original time span correctly.

**Comment by nathanielrindlaub** [comment]
Sorry I don't quite follow. So 2008 - 2018 was a mistake, because we were actually calculating an 11 year trend? Meaning 2009 - 2018 is correct?

**Comment by kklausmeyer** [comment]
Yes @nathanielrindlaub that is correct- we are trying to do a 10 year trend, so 2008-2018 was too long.  @postfalk fixed it so that 2009-2018 is the new correct timespan of 10 years.

**Comment by postfalk** [comment]
Yes, I should have known the problem. I should be called the reversed movie ticket problem. Back in the day, when we run a small film club, people sometimes calculated how much movie tickets sold incorrectly. They made the mistake to subtract the number from the first sold ticket from the number of the last sold one (instead from the number of the first one not sold). In our case have basically the reverse problem. 2018-2008 are 10 years but 11 labels. It is also the tricky difference between doing math with sets or numbers.

**Comment by nathanielrindlaub** [comment]
Done d0ead24

**Comment by kklausmeyer** [comment]
Hi @nathanielrindlaub the performance is great, but I would like a few minor tweaks.
1. Make the 2009-2018 NDVI layer on by default
2. Change the order in the legend to sort by the start date of the time window, and put the NDVI layers first, so the order would be
NDVI Trend (1985 - 2018) 
NDVI Trend (2009 - 2018)
NDVI Trend (2014 - 2018)
NDMI Trend (1985 - 2018)
NDMI Trend (2009 - 2018)
NDMI Trend (2014 - 2018)

Thanks!

**Comment by postfalk** [comment]
@nathanielrindlaub Do you think it would be a good idea to adjust the trend line to the layer selection?

**Comment by nathanielrindlaub** [comment]
@kklausmeyer - got it. Both updates are done; I'll push them live tomorrow afternoon. ca5ab1f

@postfalk - I was thinking the same thing & made those changes earlier today. Great minds :)
