### ISSUE TITLE
Toggle for GDE outlines

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/gde#117]

**Comment by nathanielrindlaub** [comment]
Done 19770e4

**Comment by kklausmeyer** [comment]
@nathanielrindlaub minor modification on this one- when I click on a polygon, the purple outline shows up under the trend raster.  Could you make it show it shows up on top so the full polygon is visible?

![image](https://user-images.githubusercontent.com/11560493/57646535-a6b4c900-7575-11e9-8383-16736ca42752.png)

**Comment by nathanielrindlaub** [comment]
Ah yeah I noticed that the other day and fixed it. Just waiting till the coast is clear to push that and some other updates live.

**Comment by kklausmeyer** [comment]
Great- thanks @nathanielrindlaub -  could you push the updates sometime this afternoon?  I'd like to be able to present the updated site tomorrow at the Napa watershed symposium.

**Comment by postfalk** [comment]
A little bit off topic but relevant. I reduced the default caching time on AWS cloudfront to 60s. So changes should be visible quicker.
