### ISSUE TITLE
Add new information to well chart pane

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#119]
Add some additional station data to the well charts:

SWN | text | State Well Number | DWR State Well Number
WELL_NAME | text | Local Well Name | Local well identification / local well name, number, or code
WCR_NO | text | WCR Number | DWR Well Completion Report Number (OSWCR Legacy Log Number)
WELL_USE | text | Well Use Type | Description of well use (Observation, Residential, etc.)

For the WCR_NO, include a hyperlink to the well completion report PDF, accessible here: https://data.ca.gov/dataset/well-completion-reports

**Comment by postfalk** [comment]
Those fields are already part of the FeatureService. I checked them

**Comment by nathanielrindlaub** [comment]
Done 4a0942c
