### ISSUE TITLE
Fix typo in info window

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#125]
Melissa caught this one:

Hey Kirk,

Just found a typo in the information box under Annual precipitation.  The water year should read “(October 1st – September 30th)” not Oct 1st to Nov 30th. See attached.

Melissa
<img width="536" alt="Screen Shot 2019-05-10 at 2 04 55 PM" src="https://user-images.githubusercontent.com/11560493/57557432-f9507400-732e-11e9-87a8-00ec63cb50c7.png">

**Comment by nathanielrindlaub** [comment]
Good catch. Fixed
