### ISSUE TITLE
Data gaps in desert polygons

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#126]
Hi @postfalk - it looks like there are some missing years in the precip data for a set of polygons in the desert.  I was doing an analsysis of the tabular data and noticed a series of missing data in the years 2004 and 2006-2010 for polygon IDs 133299-137840 (exactly 2,500 polygons).  These same data gaps don't exist in the ndvi or ndmi data table you sent, However, when I plot the data on gde pulse, I do see what looks like data gaps in the precip, ndvi, and ndmi for that time period.  Can you check it out?

![image](https://user-images.githubusercontent.com/11560493/57660543-f73f1d00-759b-11e9-9be2-1e6965886669.png)

We are also missing 1990 precip data for a smaller subset of polygons (n=159) - including 82319, 82327, 82338, 82350...

**Comment by postfalk** [comment]
I can confirm that this data has not been loaded correctly. Probably during some sort of interrupt while loading. Will fix asap.

**Comment by postfalk** [comment]
Seems to be fixed, please review and spot check other places. Also re-check whether fix for outliers is upload.
