### ISSUE TITLE
.gitignore and remove dynamically generated files from repo

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/gde#127]
Such as ```frontend/src/_site/index.html``` and others. This way it will be easier for future developers to find the place where to make changes.

Thank you, Falk

**Comment by nathanielrindlaub** [comment]
My bad. I added _site to .gitignore so that should be more clear going forward

**Comment by postfalk** [comment]
Merged this due to conflict related to me editing the wrong file first. Please double-check whether merge has been clean. Thx
