### ISSUE TITLE
Remove outlier well data

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#129]
I have found a well measurement that is an outlier and looks to be incorrect.  For stn 50285  on date 8/20/2018, it looks like they swapped the wse and gse_wse data values (see screen shot below).  I would like to use this area as an example in my demos, but the outlier is messing up the results.  Can we exclude this data value from the API?

![image](https://user-images.githubusercontent.com/11560493/57740584-69cbfd80-766d-11e9-9828-ef79a8da9288.png)

**Comment by postfalk** [comment]
a649ed4

Created a CLI command that has to be re-applied after reload of data (which should not happen too often but it is a way to keep track of this manual edits)

**Comment by postfalk** [comment]
@kklausmeyer Please double-check

**Comment by kklausmeyer** [comment]
Nice! It is working, but I realized there is another well very close-by with the same issue.  Can you do the same outlier removal for stn_id: 50284 on date 8/20/2018 ?

Thank you!

**Comment by postfalk** [comment]
sure

**Comment by postfalk** [comment]
Should be done
