### ISSUE TITLE
Should we change tabname from API to "Data & API"?

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/gde#131]
@kklausmeyer convert to task if answer is yes.

**Comment by nathanielrindlaub** [comment]
I'd prefer to keep it to one word if possible. Do you think just "Data" would suffice?

**Comment by kklausmeyer** [comment]
I like the idea of one word- "Data" will work well for our target audience since I think about 70% of them don't know what an API is.

**Comment by kklausmeyer** [comment]
Should we change the URL as well from https://gde.codefornature.org/#/api to https://gde.codefornature.org/#/data
?

**Comment by nathanielrindlaub** [comment]
Yeah I can change all 'API' references in the URL, nav links, and buttons to 'Data'

**Comment by postfalk** [comment]
I think 'Data access' on the landing page and Data in the header menu would be good  as long as we mention the API in the text of the header menu. I think we have to give the whole thing another pass for consistency.

**Comment by nathanielrindlaub** [comment]
Cool. I agree with mentioning API in the text of the header menu and being more descriptive in the little teaser title on the landing page, but I think what we currently have ("Download the Data") is a bit more clear than "Data Access". Happy to go either way though no strong opinion.

**Comment by kklausmeyer** [comment]
I think "Data Access" has a bit of overlap in meaning with the "Interactive Map".  For example, if I wanted to see the landsat data for a GDE, I might be confused which heading to click.  I think Interactive Map and Download the Data are sufficiently different for our audience, so lets use those terms. 

As a side note, I agree with Falk that "Data Access" is a better description of what the API does, but I want to push more users to the map first, and then they can dig into the download and API functions of the site if they need to.

**Comment by postfalk** [comment]
Fine with me

**Comment by postfalk** [comment]
Please implement and close out

**Comment by nathanielrindlaub** [comment]
Done 723bd24
