### ISSUE TITLE
Please review API or Data page again

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/gde#133]
With following goals:

- [ ] consistency in title, header, navigation, etc.
- [ ] I think the Data Download section should get some additional context
- [ ] Reread the whole think

**Comment by postfalk** [comment]
Pls hold off, it still takes awhile before changes are actually visible. Working on this

**Comment by postfalk** [comment]
Ok changes are up. @kklausmeyer If you are going to do a paper edit. Could you please scan and email or post here because I have to do that later from home. Will not touch the site tomorrow during your presentation.

**Comment by kklausmeyer** [comment]
I provided Falk with a paper edit and email with new content.  Please close the issue when implemented.

**Comment by postfalk** [comment]
Done
