### ISSUE TITLE
Update well symbology

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#135]
I know we have been over this before, but I think the red shallow wells gives the wrong color connotation, and it makes it confusing since we are using red to show declines as well.  I would like to move the wells to the purple family.  Here is my suggested colors:

Shallow aquifer: #8400A8
Uncertain aquifer: #DF73FF
Deep aquifer: Same as is.

Here is a mock up for reference:
![image](https://user-images.githubusercontent.com/11560493/57806114-54111380-7713-11e9-8b43-f61b9c8d3c11.png)

With aerial basemap:
![image](https://user-images.githubusercontent.com/11560493/57806156-6db25b00-7713-11e9-9929-e7771d1c431f.png)

**Comment by postfalk** [comment]
Well, done. Might take about an hour before applied. Please check and close out.

**Comment by postfalk** [comment]
Application depends on redeploy since Natty has a style override in place
