### ISSUE TITLE
Content for "Chart Help" page

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/gde#139]
I made a new chart help page ([gde.codefornature.org/#/chart-help](https://gde.codefornature.org/#/chart-help)) that I link to from the bottom of the chart panel, and I added some sample content to explain what the trend window is hand how to use it. There's also a video demoing how to move it around. It's just placeholder text, so feel free to send me edits.

What else should go on that page? Happy to make more demo vids or screenshots if it's helpful for illustrating things.

**Comment by nathanielrindlaub** [comment]
Note - this is not live yet. Waiting till @kklausmeyer wraps up his pres at the Napa Watershed symposium.

**Comment by kklausmeyer** [comment]
I'm all done with the Napa Watershed symposium.  This looks great.  I will write up some content today with some screenshots to provide some example interpretations.

**Comment by kklausmeyer** [comment]
Here is the content for the Chart Help page (pages 3-7):  https://docs.google.com/document/d/1JXQIqSZ3m-ZJ3gPuBR5wAj0HrjT3h91A47Q2W_FB8I8/edit?usp=sharing

**Comment by nathanielrindlaub** [comment]
Excellent. This looks great @kklausmeyer. Still working on the methodology section but this is next.

**Comment by nathanielrindlaub** [comment]
done. Pushing live shortly.
