### ISSUE TITLE
Update all videos ahead of 1.0 release

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/gde#140]
Styles have changed a bit so need to update. Update all videos & consider making GIFs for their fall-back cover images.

**Comment by kklausmeyer** [comment]
Thanks Natty-  one idea would be to select a GDE with a paired well nearby.  I typically select the ones on the Salinas or Santa Clara River since there is a good correlation with well data and GDE data.

**Comment by nathanielrindlaub** [comment]
Ok cool - will do.

**Comment by nathanielrindlaub** [comment]
Done

**Comment by kklausmeyer** [comment]
Thanks Natty-  can you post the file to this thread as well so we can use it in other materials!

**Comment by nathanielrindlaub** [comment]
Hey Kirk - it appears I can't upload videos to github. I'll email it to you :)

**Comment by postfalk** [comment]
You can always zip it. Falk


______________________________________________________________________

Falk Schuetzenmeister | The Nature Conservancy | m: 1-510-604-8010 | skype: falk.schuetzenmeister


________________________________
