### ISSUE TITLE
Add GW basin boundaries

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#142]
This is something we discussed in the past and decided to scrap but I am getting requests to put it in. Let’s have the basin boundaries off by default and just show a white outline and perhaps a highly transparent white fill. Here is the data if you need it. https://data.cnra.ca.gov/dataset/ca-bulletin-118-groundwater-basins  

Sorry for the last minute request and it doesn’t need to be done by Friday.

**Comment by nathanielrindlaub** [comment]
Done. Only weird thing is that b/c the symbology is white, it doesn't show up against the legend's white background when you turn the layer on. Not sure how critical that is.
