### ISSUE TITLE
Documentation table csv

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/gde#146]
I need to format some tables in the documentation so that they look similar to the ones in Kirk's email I just forwarded you. What is the appropriate place for the changes. Thanks

**Comment by nathanielrindlaub** [comment]
Sorry, I'm not quite clear on the question. What do you mean by appropriate place for the changes? Like what branch?

**Comment by postfalk** [comment]
No where should I put css overwrites/additions to the documentation.


______________________________________________________________________

Falk Schuetzenmeister | The Nature Conservancy | m: 1-510-604-8010 | skype: falk.schuetzenmeister


________________________________

**Comment by nathanielrindlaub** [comment]
the data & api documentation HTML is in src/_includes/data-view.html
I'd put the CSS in src/_sass/static.scss

**Comment by postfalk** [comment]
Thx, I look your new profile pic.
