### ISSUE TITLE
Update the methods page

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#147]
Take the content from this google doc:  https://docs.google.com/document/d/1ZjEv078TzQKTGJ5wWH64a7aQIK7cIZ--pshdnf3b-go/edit?usp=sharing

You can remove the title page.  Add a link "Download this report in PDF format" at the top.  
[GDE Pulse Methods Report 20190517.pdf](https://github.com/tnc-ca-geo/gde/files/3192789/GDE.Pulse.Methods.Report.20190517.pdf)

**Comment by nathanielrindlaub** [comment]
Done. Pushing live in 30 mins or so.
