### ISSUE TITLE
Add link to data descriptions in pop-up on map page

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#152]
Last one for today I promise!  I'd like to point users who are in the interactive map and want to download the data to a place where they can see the descirption of the data they downloaded.  So a simple link at the bottom of the popup for both GDEs and Wells that says "Learn more about the downloadable data" and links to https://gde.codefornature.org/#/data

![image](https://user-images.githubusercontent.com/11560493/57961410-9aa57000-78c3-11e9-97c2-3f653a6fdf6b.png)

**Comment by nathanielrindlaub** [comment]
Done
