### ISSUE TITLE
Please set 'tracking off' cookies on all of your browsers

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/gde#153]
Hey all, just a reminder that the app is now officially launched (I think?) and we should start suppressing our own interactions with the app so that they don't muddy up google analytics data we're collecting from real users. 

We can suppress our own interactions by setting a Local Storage variable (like a cookie, but more persistent) on **each browser** we use to access the app. Each time the app loads, it checks to see if you have the variable set, and if it finds the variable it won't send interactions to GA.

To set the variable simply go to: 
[https://gde.codefornature.org/#/setmode/development](https://gde.codefornature.org/#/setmode/development)

You may need to refresh the page with that url a couple times, but once you see the purple 'tracking off' icon in the nav bar, you're all set. This can also be reversed at any time. 

@kklausmeyer - who else internally should be aware of this and set the do-not-track variable? Would you mind spreading the word to Tanu, Melissa, others?

**Comment by kklausmeyer** [comment]
Done!  thanks Natty :)
