### ISSUE TITLE
Fix Typo on Precipitation chart

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#163]
Sally Liu noticed a typo on the precip chart on the info window:

![image](https://user-images.githubusercontent.com/11560493/60554988-1e3de380-9cef-11e9-9ec8-8852309e28bf.png)

**Comment by kklausmeyer** [comment]
On a related, but lower priority note, the video screenshots of the charts will need to be updated, including the ones on the "How to interpret the charts" page (https://gde.codefornature.org/#/chart-help) and the video on the home page (https://gde.codefornature.org/#/home)

**Comment by nathanielrindlaub** [comment]
Fixed the typo but haven't re-created all the screenshots yet. I'll create another issue for that.
