### ISSUE TITLE
Update deployment scripts

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/gde#170]
~Please move the deployment destinations:~

~s3://gde-staging.codefornature.org => s3://gde-staging.codefornature.org/dist~
~s3://gde-pulse => s3://gde.codefornature.org/dist~

**Comment by postfalk** [comment]
Update:

s3://gde-staging.codefornature.org => s3://gde-staging-codefornature-org/dist
 s3://gde-pulse => s3://gde-codefornature-org/dist

Background:

AWS automatically creates a SSL certificate for the traffic between S3 and Cloudfront. The way that certificate is created changed recently. For that reason bucket names containing dots (the way it used to be recommended) will cause trouble.

**Comment by nathanielrindlaub** [comment]
Done at 074ab68
