### ISSUE TITLE
Update author list

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#171]
Please include Ian as one of the co-authors on the https://gde.codefornature.org/#/methodology page (edit in bold below)

Suggested Citation:
Klausmeyer, Kirk R., Tanushree Biswas, Melissa M. Rohde, Falk Schuetzenmeister, Nathaniel Rindlaub, **Ian Housman,** and Jeanette K. Howard. 2019. GDE Pulse: Taking the Pulse of Groundwater Dependent Ecosystems with Satellite Data. San Francisco, California. Available at https://gde.codefornature.org.

**Comment by kklausmeyer** [comment]
Please update the PDF as well.
[GDE Pulse Methods Report 20190904.pdf](https://github.com/tnc-ca-geo/gde/files/3576087/GDE.Pulse.Methods.Report.20190904.pdf)

**Comment by nathanielrindlaub** [comment]
@kklausmeyer would you mind emailing me that pdf? for whatever reason I'm having the hardest time downloading it from github. The download just stalls out half way every time.

**Comment by nathanielrindlaub** [comment]
Done at bb84200
