### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#95]
Hi Natty-  Similar to the flows website, I'd like to do some back user tracking before our 1.0 launch at the end of the month.  Let me know if you have questions.

**Comment by nathanielrindlaub** [comment]
@kklausmeyer I'm about to implement Google Analytics tracking and was wondering if you had any specific things you'd like to track. I plan on tracking the basic stuff including:

- [ ] Page views (time spent on each page, where the user went next, etc.)
- [ ] Basemap toggle events
- [ ] Search events
- [ ] Data download events
- [ ] Layer visibility changes
- [ ] Chart date range drop-down events
- [ ] Trendline window change events

Is there anything else you'd like to track? Would it be helpful to track when a GDE and/or well gets selected?

**Comment by kklausmeyer** [comment]
Hi @nathanielrindlaub - that looks like a very exhausive list to me and looks great.  The only thing I would add would be tracking the GDE IDs that are downloaded, but that might be more of something we can track on the API.  @postfalk - do we keep a log of the queries by GDE ID?

**Comment by nathanielrindlaub** [comment]
Good thought. I think I can pass the GDE ID into google analytics when users download

**Comment by nathanielrindlaub** [comment]
Done 8dbe8ce
