### ISSUE TITLE
Include more information about GDEs in the chart panel

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gde#99]
Please include the following information about the selected GDE:

1. Vegetation mapping date (DATE_DATA_REFERS_TO)

**Comment by nathanielrindlaub** [comment]
@postfalk it looks like the vegetation mapping date isn't available on the endpoint: https://services.arcgis.com/F7DSX1DSNSiWmOqh/ArcGIS/rest/services/gdes/FeatureServer/0

Do we have to rebuild and republish that layer or should I try to find the attribute elsewhere?

**Comment by postfalk** [comment]
Oh I have to add this in. Will be there by tomorrow

**Comment by postfalk** [comment]
@nathanielrindlaub I added the field it has the somewhat awkward name date_data_ as in the original source. I have been to lazy to remap it.

**Comment by nathanielrindlaub** [comment]
Thanks Falk. Done be82c12
